# @package _global_
defaults:
  - default_classif
  - optional ablations: null
  - _self_

# ---- Run plan ----
run_plan:
  all_metrics:
    - accuracy
    - f1_score
    - balanced_accuracy
    - mcc
    - auc
    - ap
  experiments:
    - epanechnikov_adaptive
    - epanechnikov_scott
    - gaussian_adaptive
    - gaussian_scott
  
  sweep_file: sweep/classif_all_pairs.yaml