# @package _global_
defaults:
  - default_segm
  - optional ablations: null
  - _self_

# ---- Single-run scalar defaults ----
metric: dsc
summary_stat: mean
kernel: epanechnikov
adaptive_bandwidth: true
trim_bandwidth: true

# ---- Run plan ----
run_plan:
  all_metrics:
    - dsc
    - nsd
    - iou
    - boundary_iou
    - cldice
    - masd
    - assd
    - hd
    - hd_perc
  experiments:
    # - epanechnikov_adaptive_trimmed
    # - epanechnikov_adaptive
    # - epanechnikov_scott
    - epanechnikov_scott_trimmed
    # - gaussian_adaptive
    # - gaussian_scott
  sweep_file: sweep/segm_all_pairs.yaml